name: CICD

on:
  push:
    branches: [ main ]


jobs:
  test:
    runs-on: prod
    
    steps:
      - name: Unit tests
        run: |
          cp .env.example .env
          composer install
          php artisan key:generate
          vendor/bin/phpunit

  deploy:
    runs-on: prod
    
    steps:
      - name: Deplying script into production enviroment
        run: |
          eval `ssh-agent -s`
          ssh-add <(echo "$SSH_PRIVATE_KEY")
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          vendor/bin/envoy run deploy --commit="$CI_COMMIT_SHA" --repository="git@$CI_SERVER_HOST:/$CI_PROJECT_PATH.git" --production="deployer@$PRODUCTION" --phpfpm="$PHPFPM" --appdir="$APP_DIR"
